### ISSUE TITLE
/usr/bin/ld: cannot find -lqrencode

### ISSUE THREAD

**Issue by zikozix** [Omnicoin-Project/Omnicoin#31]
i get this error when i do make to install omnicoin-qt
/usr/bin/ld: cannot find -lqrencode
collect2:ld returned 1 exit status
male: *** [omnicoin-qt] error 1

**Comment by MeshCollider** [comment]
Omnicoin is no longer active nor supported, why are you trying to build it?

**Comment by zikozix** [comment]
isnt it price high?

**Comment by SteenSchutt** [comment]
It's value is more or less zero, I wouldn't bother :) On 14 Oct 2017 02:20, zikozix <notifications@github.com> wrote:isnt it price high?

**Comment by meshcollider** [comment]
Actually he's right @DoctorBlue @caffeinewriter whats up with this:
https://www.coingecko.com/en/price_charts/omnicoin/usd
$26 per coin lol. Has someone relaunched it? Probably a bug

**Comment by SteenSchutt** [comment]
Such a price would be insane, given how easy it is to mine. Also if you look at the exchange they claim it's listed at, it's not there.
https://www.coingecko.com/en/coins/omnicoin/trading_exchanges

As for the actual error, if you'd insist on compiling it, you can just compile it without QR support.

**Comment by zikozix** [comment]
how can i compile it without QR support?
the price is hight here too https://bittrex.com/
i have more then 200 OMC

**Comment by zikozix** [comment]
https://themerkle.com/omni-token-value-triples-in-past-24-hours-but-no-one-knows-why/

this what happen when i do put : "make" in command to make omnicoin-qt

**Comment by zikozix** [comment]
http://postimg.org/image/5irwfqmubf/10c4edbe/

**Comment by meshcollider** [comment]
@zikozix I think you're confused between Omnicoin (OMC) and Omni Token (OMNI)

**Comment by zikozix** [comment]
@MeshCollider no no, even in bitrex the price is high not sure why i am OMC i am sure of it
http://coinofview.com/images/screenshot/jpg/omc.jpg
this is what i have '( more coins ofc about 200)

**Comment by SteenSchutt** [comment]
First of all, the article you mention, is about Omni Token, like MeshCollider says. Second, I just checked on the state of Omnicoin, someone seems to have been mining it a few days ago, since I received a few blocks when I started up the client. I can only find a single node other than my server, which makes i pretty obvious that this is not the coin people are talking about, and not the one listed on exchanges.

If I hadn't removed ABE from my server, I would have started it up, to show you how dead the blockchain is, but you can also look at this comparison and see that Omnicoin is not being traded anywhere, and most likely won't be at any point in time. It's simply too outdated.
http://coinofview.com/comparative.php?OMC,OMNI
